### ISSUE TITLE
Educational and technical video script

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/training#7]
Hi! I am collecting information for educational and technical videos (asyncapi/community#155) and would like to start writing the scripts. 

For this, how do you think is better to organize it? Creating a new repo or in this one? Any other suggestions?

Thanks in advance!

CC: @derberg @alequetzalli @fmvilas @boyney123

**Comment by derberg** [comment]
Since scripts should anyway be available in the website UI next to the video (for SEO and people that do not watch but read), then I think `website` repo is the best. We can just create a new directory for scripts only and then refactor the structure depending on what we need. For sure GH is best as we keep history and get collaboration on PR out of the box, would not like to learn new tool for it.

I wonder what others think though

**Comment by fmvilas** [comment]
Yeah, I think Github PRs are fine. I've tried Notion lately but honestly the experience hasn't been good when it comes to managing comments and suggestions. It's great for authoring tho.

**Comment by Barbanio** [comment]
> I think in both /training and /website repoes, because I see Lukasz's point, but I also think that the /training repo should include all relevant materials, and that includes our scripts.

I believe that this make sense.

**Comment by derberg** [comment]
ok, but `training` is first, I mean when work is done and original files are stored, and in `website` we just get a copy, through automation, like we do with spec or TSC list. Right @alequetzalli @Barbanio ?

**Comment by alequetzalli** [comment]
> 

Yes, this sounds great 😀👍🏽👍🏽

**Comment by alequetzalli** [comment]
> ok, but `training` is first, I mean when work is done and original files are stored, and in `website` we just get a copy, through automation, like we do with spec or TSC list. Right @alequetzalli @Barbanio ?

Yes, this sounds great 😀👍🏽👍🏽

**Comment by Barbanio** [comment]
It was concluded that the best place to work on the scripts is in the training repository.
